services:
 
  mariadb:
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql  

  adminer:
    image: adminer
    restart: always
    container_name: adminer_container
    links:
      - mariadb
    ports:
      - "8080:8080"      

volumes:
  mariadb:
